### ISSUE TITLE
Escaping single and double quotes

### ISSUE THREAD

**Issue by william-fiset** [william-fiset/COMP4951_site#1]
We need to make sure we escape the sanitize/escape quotes when sending a query to the DB otherwise the query may fail. This will be very problematic once we start sending code to the DB as code almost certainly contains contain extra quotes that will break the query string.

**Comment by micahstairs** [comment]
I'm pretty sure there's a built-in function we can use to sanitize the strings for SQL.

**Comment by william-fiset** [comment]
Actually you're right. There exist functions such as addslashes and stripslashes! I will investigate further..
